<h1><center> Introduction to Python and GitHub </center></h1>

<h3><center> 14/10/2019 </center></h3>
<img align="left" src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" width="300">
<img align="right" src="https://image.flaticon.com/icons/svg/25/25231.svg" width="300"/>

<h1><center> Timeline </center></h1>

* ### 11 - 12: Intro to Python part 1 & 2
* ### 12 - 12.45: Lunch
* ### 12.45 - 13.15: Intro to Python part 2 (cont.)
* ### 13.15 - 14: Intro to Python part 3
* ### 14 - 14.30: Intro to Python part 4
* ### 14.30 - 15: Intro to GitHub


<h1><center> Introduction to Python part 1 </center></h1>

* ### Lists
* ### NumPy
* ### Loops


<h1><center> Lists </center></h1>
<h3><center> Defining, appending and removing </center></h3>

In [1]:
List = [1, 2, 3]
print(List)

[1, 2, 3]


In [2]:
Tuple = (1, 2, 3)
print(Tuple)

List = list(Tuple)
print(List)

(1, 2, 3)
[1, 2, 3]


In [3]:
print(len(List))

3


In [4]:
List.append(4)
print(List)

[1, 2, 3, 4]


In [5]:
List.append([5, 6])
print(List)

[1, 2, 3, 4, [5, 6]]


In [6]:
List.extend([7, 8]) # alternative: List += [7, 8]
print(List) 

[1, 2, 3, 4, [5, 6], 7, 8]


In [7]:
List.extend(["A", "B", {"X":1, "Y":2}, (9, 10), 11])
print(List)

[1, 2, 3, 4, [5, 6], 7, 8, 'A', 'B', {'X': 1, 'Y': 2}, (9, 10), 11]


In [8]:
removed_element = List.pop(0)
print('After removing first element:', List)
print('Removed element:', removed_element)

After removing first element: [2, 3, 4, [5, 6], 7, 8, 'A', 'B', {'X': 1, 'Y': 2}, (9, 10), 11]
Removed element: 1


In [9]:
del List[:]
print(List)

[]


<h1><center> Lists </center></h1>
<h3><center> Indices and slicing </center></h3>

In [11]:
List = list(range(10))
print(range(10))
print(List)

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
print('First element:', List[0])
print('Last element:', List[9])
print('"-1" element:', List[-1])

First element: 0
Last element: 9
"-1" element: 9


In [13]:
print('First four elements:', List[:4])

First four elements: [0, 1, 2, 3]


In [14]:
print('Last three elements:', List[-3:])

Last three elements: [7, 8, 9]


In [16]:
print('Full list:', List, "\n")
print('Every other element:', List[1:7:2], "\n")
print('Every second other element:', List[::3], "\n")

Full list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 

Every other element: [1, 3, 5] 

Every second other element: [0, 3, 6, 9] 



In [17]:
print('Reversed list:', List[::-1], "\n")

Reversed list: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0] 



<h1><center> Lists </center></h1>
<h3><center> Changing elements </center></h3>

In [18]:
names = ['Curie', 'Darwing', 'Turing']  # typo in Darwin's name

print('Names originally:', names)

names[1] = 'Darwin'  # correct the name

print('Corrected version:', names)

Names originally: ['Curie', 'Darwing', 'Turing']
Corrected version: ['Curie', 'Darwin', 'Turing']


In [19]:
name = 'Darwin'
name[0] = 'd'

TypeError: 'str' object does not support item assignment

In [20]:
salsa = ['peppers', 'onions', 'tomatoes']

my_salsa = salsa        # <-- my_salsa and salsa point to the *same* list data in memory

salsa[0] = 'hot peppers'

print('Ingredients in my salsa:', my_salsa)

Ingredients in my salsa: ['hot peppers', 'onions', 'tomatoes']


In [21]:
salsa = ['peppers', 'onions', 'tomatoes']

my_salsa = list(salsa)        # <-- makes a *copy* of the list

salsa[0] = 'hot peppers'

print('Ingredients in my salsa:', my_salsa)

Ingredients in my salsa: ['peppers', 'onions', 'tomatoes']


<h1><center> Lists </center></h1>
<h3><center> Nested lists </center></h3>

In [22]:
nested_list = [
            ['pepper', 'zucchini', 'onion'],
            ['cabbage', 'lettuce', 'garlic'],
            ['apple', 'pear', 'banana']
        ]

In [23]:
print(nested_list[0])

['pepper', 'zucchini', 'onion']


In [24]:
print(nested_list[0][0])

pepper


In [25]:
empty_list = [[], [], []]

empty_list[0].append(1)
empty_list[1].extend([2,3])
empty_list[2].extend([4,5,6])

print(empty_list)


[[1], [2, 3], [4, 5, 6]]


In [26]:
print(len(empty_list))

3


<h1><center> NumPy </center></h1>

<h1><center> NumPy </center></h1>
<h3><center> Arrays and attributes </center></h3>

In [217]:
import numpy as np

In [27]:
List = [[1, 2, 3], [4, 5, 6]]
Array = np.array(List)

print(type(Array))

<class 'numpy.ndarray'>


In [30]:
linspace_array = np.linspace(0, 10, 11) # start, end, num of points
print(linspace_array)

arange_array = np.arange(0, 11, 1) # start, end + step, step
print(arange_array)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [33]:
array_of_zeros = np.zeros(3)
print(array_of_zeros)

[0. 0. 0.]


array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [34]:
array_of_ones = np.ones((3, 4, 5))
print(array_of_ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [38]:
# Examine key array attributes
print("Dimensions ", array_of_ones.ndim)    # number of dim
print("Shape      ", array_of_ones.shape)  # number of elements in each dim
print("Size       ", array_of_ones.size)   # total number of elements
print("Data type  ", array_of_ones.dtype)  # data type of element e.g. 64 bit float

Dimensions  3
Shape       (3, 4, 5)
Size        60
Data type   float64


In [228]:
print(List, "\n")
print(Array, "\n")

print(List[0][2])
print(Array[0][2])
print(Array[0, 2])

[[1, 2, 3], [4, 5, 6]] 

[[1 2 3]
 [4 5 6]] 

3
3
3


In [40]:
# Make a copy of Array

Array = np.array(["A", "B"])
Array_2 = Array

Array[1] = "C"
print(Array_2)


['A' 'C']


In [50]:
Array = np.array([["A", "B"], ["D", "E"]])
Array_2 = Array.copy()
# Array_3 = np.deepcopy(Array)
Array[1,1] = "C"
print(Array_2)
# print(Array_3)

[['A' 'B']
 ['D' 'E']]


<h1><center> NumPy </center></h1>
<h3><center> Loading and saving files </center></h3>

In [53]:
data = np.loadtxt("importme.txt", skiprows=1, unpack=True, delimiter="\t")

print(data)
print(np.shape(data))

[[ 0.  1.  2.  3.  4.  5.]
 [10. 20. 30. 40. 50. 60.]]
(2, 6)


In [233]:
np.savetxt("exportme.txt", np.transpose(data))

<h1><center> Loops </center></h1>

In [54]:
word = 'world'
print(word[0])
print(word[1])
print(word[2])
print(word[3])
print(word[4])

w
o
r
l
d


<h1><center> Loops </center></h1>
<h3><center> For loops </center></h3>

In [56]:
word = "world"
for mohamed in word:
    print(mohamed)

w
o
r
l
d


In [59]:
length = 0

for vowel in 'aeiou':
    
    if length == 2:
        print(vowel)
        
    length = length + 1 # or: length += 1

print('There are', length, 'vowels')

i
There are 5 vowels


In [61]:
word = "Mars"

array = [1, 2, 3, 4]

for num, char in enumerate(word, 1):
    print(num, char)
    array[num] = 7

1 M
2 a
3 r
4 s


In [62]:
# Example: Take the square of only odd numbers in some_list

some_list = np.arange(1, 11, 1)
print(some_list)

some_list2 = []
for number in some_list:
    if number % 2 != 0: # number is odd
        some_list2.append(number**2)
    
some_list3 = [number**2 for number in some_list if number % 2 != 0]

print(some_list2)
print(some_list3)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 9, 25, 49, 81]
[1, 9, 25, 49, 81]


<h1><center> Loops </center></h1>
<h3><center> While loops </center></h3>

In [63]:
for i in range(5):
    print(i)


print("\n")

i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


0
1
2
3
4


<h1><center> End of part 1 </center></h1>